{% set name = "django-modeladmin-reorder" %}
{% set version = "0.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "bf42d0dcd184b796b4d6d988c4b4cea7914adfc4430dd9978a8a0199051f189f"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - django
    - pip
    - python
  run:
    - django
    - python

test:
  imports:
    - admin_reorder

about:
  home: "https://github.com/mishbahr/django-modeladmin-reorder"
  license: "BSD"
  license_family: "BSD"
  license_file: ""
  summary: "Custom ordering for the apps and models in the admin app."
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - your-github-id-here
